import 'package:flutter/material.dart';
import 'package:login_app/core/constant/color.dart';

final themeData = ThemeData(
    useMaterial3: true,
    primaryColor: ColorManager.primaryColor,
    fontFamily: 'Urbanist',
    appBarTheme: AppBarTheme(
      backgroundColor: ColorManager.primaryColor,
    ),
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF476800),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFB3F733),
      onPrimaryContainer: Color(0xFF121F00),
      secondary: Color(0xFF5555A9),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE2DFFF),
      onSecondaryContainer: Color(0xFF0E0664),
      tertiary: Color(0xFF476800),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFB3F733),
      onTertiaryContainer: Color(0xFF121F00),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFEFCF4),
      onBackground: Color(0xFF1B1C18),
      surface: Color(0xFFFEFCF4),
      onSurface: Color(0xFF1B1C18),
      surfaceVariant: Color(0xFFE2E4D4),
      onSurfaceVariant: Color(0xFF45483D),
      outline: Color(0xFF75786C),
      onInverseSurface: Color(0xFFF2F1E9),
      inverseSurface: Color(0xFF30312C),
      inversePrimary: Color(0xFF98DA03),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF476800),
      outlineVariant: Color(0xFFC5C8B9),
      scrim: Color(0xFF000000),
    ),
    scaffoldBackgroundColor: const Color(0xFFF8FAFC));
